#!/bin/sh
set -eu

__ln() {
  set -- "$(realpath -- "$1")" "$(realpath -- "$2")"
  [ "$1" = "$2" ] && return 0
  [ -e "$2" ] && mv "$2" "$2.bak"
  ln -s "$1" "$2"
}

# for bash and Readline
__ln ".bashrc" "$HOME/.bashrc"
__ln ".inputrc" "$HOME/.inputrc"

# for vim
__ln ".vimrc" "$HOME/.vimrc"
[ -d "$HOME/.vim" ] || mkdir "$HOME/.vim"
__ln ".vim/after" "$HOME/.vim/after"
__ln ".vim/pack" "$HOME/.vim/pack"
__ln ".vim/statusline.vim" "$HOME/.vim/statusline.vim"

# setup for commit message template
__ln ".commit_template" "$HOME/.commit_template"
